"""initial schema

Revision ID: c63ee94dcc3d
Revises: 
Create Date: 2026-06-03 10:57:09.836303

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c63ee94dcc3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=True)
    op.create_table('platform_knowledge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('generation_type', sa.String(length=50), nullable=False),
    sa.Column('feature_category', sa.String(length=100), nullable=True),
    sa.Column('pattern_text', sa.Text(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_knowledge_feature_category'), 'platform_knowledge', ['feature_category'], unique=False)
    op.create_index(op.f('ix_platform_knowledge_generation_type'), 'platform_knowledge', ['generation_type'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('shared_credit_pool', sa.Integer(), nullable=False),
    sa.Column('credits_used_month', sa.Integer(), nullable=False),
    sa.Column('classified_mode', sa.Boolean(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('team_invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('user_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('team_role', sa.String(length=20), nullable=True),
    sa.Column('credit_balance', sa.Integer(), nullable=False),
    sa.Column('credits_used_month', sa.Integer(), nullable=False),
    sa.Column('credits_used_total', sa.Integer(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('classified_mode', sa.Boolean(), nullable=False),
    sa.Column('billing_name', sa.String(length=255), nullable=True),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('billing_vat', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_accounts_email'), 'user_accounts', ['email'], unique=True)
    op.create_table('credit_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('txn_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('generation_type', sa.String(length=50), nullable=True),
    sa.Column('layer_used', sa.String(length=10), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('generation_type', sa.String(length=50), nullable=False),
    sa.Column('jira_issue_key', sa.String(length=50), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('layer_used', sa.String(length=10), nullable=False),
    sa.Column('credits_charged', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('billing_name', sa.String(length=255), nullable=False),
    sa.Column('billing_address', sa.Text(), nullable=True),
    sa.Column('billing_vat', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('credits_purchased', sa.Integer(), nullable=False),
    sa.Column('amount_net', sa.Integer(), nullable=False),
    sa.Column('vat_rate', sa.Integer(), nullable=False),
    sa.Column('vat_amount', sa.Integer(), nullable=False),
    sa.Column('amount_gross', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('user_context',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('generation_type', sa.String(length=50), nullable=False),
    sa.Column('feature_summary', sa.Text(), nullable=True),
    sa.Column('artifact_pattern', sa.Text(), nullable=True),
    sa.Column('is_classified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_index', sa.Integer(), nullable=False),
    sa.Column('generation_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('human_approved', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('xray_issue_key', sa.String(length=50), nullable=True),
    sa.Column('pushed_to_xray', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artifacts')
    op.drop_table('user_context')
    op.drop_table('invoices')
    op.drop_table('generation_jobs')
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_user_accounts_email'), table_name='user_accounts')
    op.drop_table('user_accounts')
    op.drop_table('team_invites')
    op.drop_table('teams')
    op.drop_index(op.f('ix_platform_knowledge_generation_type'), table_name='platform_knowledge')
    op.drop_index(op.f('ix_platform_knowledge_feature_category'), table_name='platform_knowledge')
    op.drop_table('platform_knowledge')
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
